# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    form: "\n  - trigger: \"{{match}}\"\n    replace:"
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"
  #american dates
  - trigger: ":adate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  # Day
  - trigger: ":day"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d"
  # ISO-Date
  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M"
  # Dates for OrgMode
  - trigger: ":odate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "[%Y-%m-%d]"


  # latex
  - trigger: "\\pd "
    form: \frac{\partial {{num}}}{\partial {{denum}}}
  - trigger: "\\pdc "
    form: \left(\frac{\partial {{num}}}{\partial {{denum}}}\right)_{{index}}
  - trigger: ":x "
    replace: "$x$"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"


  - trigger: '@tw'
    replace: 'tassilo.neubauer@web.de'
  - trigger: '@tg'
    replace: 'tassilo.neubauer@gmail.com'
  - trigger: 'gtasse'
    replace: "Gr√º√üe\n\nTassilo"
  - trigger: 'mfg'
    replace: "Mit freundlichen Gr√º√üen\n\nTassilo Neubauer"
  - trigger: "ill"
    replace: "i‚Äôll"
    propagate_case: true
    word: true
    
  - trigger: ":TN"
    replace: "Tassilo Neubauer"
  - trigger: ":tn"
    replace: "tassilo neubauer"
  - trigger: ":sws."
    replace: "üòÖ"
  - trigger: "Rn"
    replace: "‚Ñù‚Åø"
  - trigger: ":github"
    replace: "git@github.com:sonofhypnos/"
  - trigger: ":windows."
    replace: "ÔÖ∫"
  - trigger: "enumerate"
    replace: "list"
  - trigger: "moloch"
    replace: "coordination problem"
  - trigger: "ontology"
    replace: "world-view"
  - trigger: "agenty"
    replace: "proactive"
  - trigger: "heuristic"
    replace: "rule of thumb"
  - trigger: "order of magnitue"
    replace: "10 times bigger"
  - trigger: "epistemic status"
    replace: "Confidence level"
  - trigger: "viable"
    replace: "practical"
  - trigger: "utilise"
    replace: "use"
  - trigger: "retain"
    replace: "keep"
  - trigger: "irregardless"
    replace: "regardless"
  - trigger: "hitherto"
    replace: "until now"
  - trigger: "henceforth"
    replace: "from now on"
  - trigger: "exhibit"
    replace: "show"
  - trigger: "assidiuously"
    replace: "actively"
  - trigger: "backround"
    replace: "background"
  - trigger: ":fnr"
    replace: '00000050878.5'
  - trigger: ":hg"
    replace: "Herzliche Gr√º√üe\nTassilo"
  - trigger: ":hg"
    replace: "Liebe Gr√º√üe\nTassilo"
  - trigger: ":gt"
    replace: "Gr√º√üe\nTassilo"
